# Copyright 2025 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# models.py
import sqlalchemy as sa
from sqlalchemy.orm import relationship
from sqlalchemy.schema import FetchedValue
from sqlalchemy.types import ARRAY, LargeBinary, String, Text

from datacommons_db.models.base import Base

NODE_TABLE_NAME = "Node"


class NodeRecord(Base):
    __tablename__ = NODE_TABLE_NAME

    # Primary Key
    # autoincrement=False: subject_id is a preallocated DCID, not a sequence generated by the database.
    subject_id = sa.Column(sa.String(1024), primary_key=True, autoincrement=False)
    namespace_name = sa.Column(sa.String(128), nullable=False, default="local")

    # Use String() for STRING(MAX); matches DDL nullability
    name = sa.Column(sa.String(), nullable=False, default="")
    value = sa.Column(sa.String(), nullable=False, default="")
    bytes = sa.Column(sa.LargeBinary(), nullable=False, default=b"")
    types = sa.Column(ARRAY(sa.String(1024)), nullable=False, default=[])

    # Relationships
    outgoing_edges = relationship(
        "EdgeRecord",
        foreign_keys="EdgeRecord.subject_id",
        back_populates="source_node",
        lazy="selectin",
        cascade="all, delete-orphan",
    )

    incoming_edges = relationship(
        "EdgeRecord",
        foreign_keys="EdgeRecord.object_id",  # Crucial: links to the object_id FK
        back_populates="target_node",  # Points to the matching relationship in EdgeRecord
        lazy="selectin",
        cascade="all, delete-orphan",
    )

    __table_args__ = (sa.Index("NodeByNamespace", namespace_name),)

    def __repr__(self):
        return (
            "<NodeRecord("
            f"subject_id='{self.subject_id}', namespace_name='{self.namespace_name}', "
            f"name='{self.name}')>"
        )
